# Copyright 2011-2012 Amazon.com, Inc. or its affiliates. All Rights Reserved.

source 'http://rubygems.org'

gem 'rails', '~> 3.0.6'
gem 'aws-sdk', '~> 0.1.0'
gem 'haml', '~> 3.0.18'
gem "sqlite3-ruby", :require => "sqlite3"
gem "memory_test_fix"
gem "jquery-rails"
gem "rdiscount"

group :development, :test do
  gem "cucumber-rails"
  gem "capybara"
  gem "rspec-rails"
end
