# frozen_string_literal: true

# WARNING ABOUT GENERATED CODE
#
# This file is generated. See the contributing guide for more information:
# https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md
#
# WARNING ABOUT GENERATED CODE

module Aws::ResourceExplorer2
  class EndpointProvider
    def initialize(rule_set = nil)
      @@rule_set ||= begin
        endpoint_rules = Aws::Json.load(Base64.decode64(RULES))
        Aws::Endpoints::RuleSet.new(
          version: endpoint_rules['version'],
          service_id: endpoint_rules['serviceId'],
          parameters: endpoint_rules['parameters'],
          rules: endpoint_rules['rules']
        )
      end
      @provider = Aws::Endpoints::RulesProvider.new(rule_set || @@rule_set)
    end

    def resolve_endpoint(parameters)
      @provider.resolve_endpoint(parameters)
    end

    # @api private
    RULES = <<-JSON
eyJ2ZXJzaW9uIjoiMS4wIiwicGFyYW1ldGVycyI6eyJSZWdpb24iOnsiYnVp
bHRJbiI6IkFXUzo6UmVnaW9uIiwicmVxdWlyZWQiOmZhbHNlLCJkb2N1bWVu
dGF0aW9uIjoiVGhlIEFXUyByZWdpb24gdXNlZCB0byBkaXNwYXRjaCB0aGUg
cmVxdWVzdC4iLCJ0eXBlIjoiU3RyaW5nIn0sIlVzZUZJUFMiOnsiYnVpbHRJ
biI6IkFXUzo6VXNlRklQUyIsInJlcXVpcmVkIjp0cnVlLCJkZWZhdWx0Ijpm
YWxzZSwiZG9jdW1lbnRhdGlvbiI6IldoZW4gdHJ1ZSwgc2VuZCB0aGlzIHJl
cXVlc3QgdG8gdGhlIEZJUFMtY29tcGxpYW50IHJlZ2lvbmFsIGVuZHBvaW50
LiBJZiB0aGUgY29uZmlndXJlZCBlbmRwb2ludCBkb2VzIG5vdCBoYXZlIGEg
RklQUyBjb21wbGlhbnQgZW5kcG9pbnQsIGRpc3BhdGNoaW5nIHRoZSByZXF1
ZXN0IHdpbGwgcmV0dXJuIGFuIGVycm9yLiIsInR5cGUiOiJCb29sZWFuIn0s
IkVuZHBvaW50Ijp7ImJ1aWx0SW4iOiJTREs6OkVuZHBvaW50IiwicmVxdWly
ZWQiOmZhbHNlLCJkb2N1bWVudGF0aW9uIjoiT3ZlcnJpZGUgdGhlIGVuZHBv
aW50IHVzZWQgdG8gc2VuZCB0aGlzIHJlcXVlc3QiLCJ0eXBlIjoiU3RyaW5n
In19LCJydWxlcyI6W3siY29uZGl0aW9ucyI6W3siZm4iOiJhd3MucGFydGl0
aW9uIiwiYXJndiI6W3sicmVmIjoiUmVnaW9uIn1dLCJhc3NpZ24iOiJQYXJ0
aXRpb25SZXN1bHQifV0sInR5cGUiOiJ0cmVlIiwicnVsZXMiOlt7ImNvbmRp
dGlvbnMiOlt7ImZuIjoiaXNTZXQiLCJhcmd2IjpbeyJyZWYiOiJFbmRwb2lu
dCJ9XX0seyJmbiI6InBhcnNlVVJMIiwiYXJndiI6W3sicmVmIjoiRW5kcG9p
bnQifV0sImFzc2lnbiI6InVybCJ9XSwidHlwZSI6InRyZWUiLCJydWxlcyI6
W3siY29uZGl0aW9ucyI6W3siZm4iOiJib29sZWFuRXF1YWxzIiwiYXJndiI6
W3sicmVmIjoiVXNlRklQUyJ9LHRydWVdfV0sImVycm9yIjoiSW52YWxpZCBD
b25maWd1cmF0aW9uOiBGSVBTIGFuZCBjdXN0b20gZW5kcG9pbnQgYXJlIG5v
dCBzdXBwb3J0ZWQiLCJ0eXBlIjoiZXJyb3IifSx7ImNvbmRpdGlvbnMiOltd
LCJlbmRwb2ludCI6eyJ1cmwiOnsicmVmIjoiRW5kcG9pbnQifSwicHJvcGVy
dGllcyI6e30sImhlYWRlcnMiOnt9fSwidHlwZSI6ImVuZHBvaW50In1dfSx7
ImNvbmRpdGlvbnMiOltdLCJ0eXBlIjoidHJlZSIsInJ1bGVzIjpbeyJjb25k
aXRpb25zIjpbeyJmbiI6ImJvb2xlYW5FcXVhbHMiLCJhcmd2IjpbdHJ1ZSx7
ImZuIjoiZ2V0QXR0ciIsImFyZ3YiOlt7InJlZiI6IlBhcnRpdGlvblJlc3Vs
dCJ9LCJzdXBwb3J0c0R1YWxTdGFjayJdfV19XSwidHlwZSI6InRyZWUiLCJy
dWxlcyI6W3siY29uZGl0aW9ucyI6W3siZm4iOiJib29sZWFuRXF1YWxzIiwi
YXJndiI6W3sicmVmIjoiVXNlRklQUyJ9LHRydWVdfV0sInR5cGUiOiJ0cmVl
IiwicnVsZXMiOlt7ImNvbmRpdGlvbnMiOlt7ImZuIjoiYm9vbGVhbkVxdWFs
cyIsImFyZ3YiOlt0cnVlLHsiZm4iOiJnZXRBdHRyIiwiYXJndiI6W3sicmVm
IjoiUGFydGl0aW9uUmVzdWx0In0sInN1cHBvcnRzRklQUyJdfV19XSwidHlw
ZSI6InRyZWUiLCJydWxlcyI6W3siY29uZGl0aW9ucyI6W10sImVuZHBvaW50
Ijp7InVybCI6Imh0dHBzOi8vcmVzb3VyY2UtZXhwbG9yZXItMi1maXBzLntS
ZWdpb259LntQYXJ0aXRpb25SZXN1bHQjZHVhbFN0YWNrRG5zU3VmZml4fSIs
InByb3BlcnRpZXMiOnt9LCJoZWFkZXJzIjp7fX0sInR5cGUiOiJlbmRwb2lu
dCJ9XX0seyJjb25kaXRpb25zIjpbXSwiZXJyb3IiOiJGSVBTIGlzIGVuYWJs
ZWQgYnV0IHRoaXMgcGFydGl0aW9uIGRvZXMgbm90IHN1cHBvcnQgRklQUyIs
InR5cGUiOiJlcnJvciJ9XX0seyJjb25kaXRpb25zIjpbXSwiZW5kcG9pbnQi
OnsidXJsIjoiaHR0cHM6Ly9yZXNvdXJjZS1leHBsb3Jlci0yLntSZWdpb259
LntQYXJ0aXRpb25SZXN1bHQjZHVhbFN0YWNrRG5zU3VmZml4fSIsInByb3Bl
cnRpZXMiOnt9LCJoZWFkZXJzIjp7fX0sInR5cGUiOiJlbmRwb2ludCJ9XX0s
eyJjb25kaXRpb25zIjpbXSwidHlwZSI6InRyZWUiLCJydWxlcyI6W3siY29u
ZGl0aW9ucyI6W3siZm4iOiJib29sZWFuRXF1YWxzIiwiYXJndiI6W3sicmVm
IjoiVXNlRklQUyJ9LHRydWVdfV0sInR5cGUiOiJ0cmVlIiwicnVsZXMiOlt7
ImNvbmRpdGlvbnMiOlt7ImZuIjoiYm9vbGVhbkVxdWFscyIsImFyZ3YiOlt0
cnVlLHsiZm4iOiJnZXRBdHRyIiwiYXJndiI6W3sicmVmIjoiUGFydGl0aW9u
UmVzdWx0In0sInN1cHBvcnRzRklQUyJdfV19XSwidHlwZSI6InRyZWUiLCJy
dWxlcyI6W3siY29uZGl0aW9ucyI6W10sImVuZHBvaW50Ijp7InVybCI6Imh0
dHBzOi8vcmVzb3VyY2UtZXhwbG9yZXItMi1maXBzLntSZWdpb259LntQYXJ0
aXRpb25SZXN1bHQjZG5zU3VmZml4fSIsInByb3BlcnRpZXMiOnt9LCJoZWFk
ZXJzIjp7fX0sInR5cGUiOiJlbmRwb2ludCJ9XX0seyJjb25kaXRpb25zIjpb
XSwiZXJyb3IiOiJGSVBTIGlzIGVuYWJsZWQgYnV0IHRoaXMgcGFydGl0aW9u
IGRvZXMgbm90IHN1cHBvcnQgRklQUyIsInR5cGUiOiJlcnJvciJ9XX0seyJj
b25kaXRpb25zIjpbXSwiZW5kcG9pbnQiOnsidXJsIjoiaHR0cHM6Ly9yZXNv
dXJjZS1leHBsb3Jlci0yLntSZWdpb259LntQYXJ0aXRpb25SZXN1bHQjZG5z
U3VmZml4fSIsInByb3BlcnRpZXMiOnt9LCJoZWFkZXJzIjp7fX0sInR5cGUi
OiJlbmRwb2ludCJ9XX1dfV19XX0=

    JSON
  end
end
