name: Benchmark

on:
  push:
    branches:
      - version-3

  pull_request:
    branches:
      - version-3

permissions:
  id-token: write # required for OIDC
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      GH_EVENT: ${{github.event_name}}
      GH_REF: ${{github.head_ref}}
      GH_REPO: ${{github.repository}}
      EXECUTION_ENV: github-action
    strategy:
      fail-fast: false
      matrix:
        ruby: [jruby-9.4, 3.3]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install gems
        run: |
          bundle config set --local without 'development docs rbs repl'
          bundle install

      - name: Build SDK
        run: bundle exec rake build

      - name: Benchmark Gems
        env:
          JRUBY_OPTS: -J-Xmx4g
        run: bundle exec rake benchmark:run

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::373952703873:role/BenchmarkReporter
          role-session-name: benchmark-reporter
          aws-region: us-east-1

      - name: Upload benchmark report
        run: bundle exec rake benchmark:upload-report

      - name: Put benchmark metrics
        run: bundle exec rake benchmark:put-metrics
